# Generated by Django 5.2.8 on 2026-08-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
    ]
